### ISSUE TITLE
Provide a way to get a link to a thread or to a post

### ISSUE THREAD

**Issue by rouazana** [TwakeApp/Twake#181]
Sometimes I want to share a previous post on an other channel. It's then very handful to be able to provide a link to this post.

Sometimes I want to bookmark a post in my browser. Here also it's very handful to be able to directly bookmark a post, or even just open it in a new browser tab or a new browser window.

# User stories

As a user, I want to share a post. When I click to the date of a message, a new window open with this post in the middle of the screen.

**Comment by hantt12** [comment]
My observation: 

1. The message is not shown in the middle of the screen. It is shown at the top

2. In my opinion, it is a very good idea to provide a link to the message. However, adding the link to the time of the message is not a good idea because it is not friendly to user (they may not notice that there is a link in the time). How about adding "Copy link" option the same way as Edit and Delete option?

![20201001_1.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/a86cfd31-c1b9-495e-9b0d-61e6daaaf9e0)

**Comment by RomaricMourgues** [comment]
1. Yes it is, but should be entirely visible from the thread subject. If they is scroll issues, can you create an other issue ?

2. There is a "Copy link" but only on thread subjects, not in responses. I want it that way because we cannot yet have a jump to an answer.

I just noticed there is an error when trying to open the side view for a message without answers, may be we need to re)create an issue for this.

**Comment by hantt12** [comment]
thanks for your answer. I have created an issue for it at https://app.zenhub.com/workspaces/twake-5f06c5bf7796310019354875/issues/twakeapp/twake/339
