### ISSUE TITLE
main contents overlaps right sidebar contents when it contains code snippet

### ISSUE THREAD

**Issue by MichaelBailly** [TwakeApp/Twake#202]
**Describe the bug**
When the main channel discussion contains code snippets (enclosed with three backtits), and there is another discussion open in the right side panel, the main panel contents is not bound and overlaps at the background of the right side panel

**To Reproduce**
1. On channel1, write a message with a code snippet (enclosed in three backtits). Make sure the code snippet line is long enough (around 200 chars or more)
2. On channel 2, have a thread discussion. USe "see all answers" link to open the thread in the right sidebar
3. Go back to channel1

**Expected behavior**
Channel1 contents is in the middle
Channel2 contents is on the right sidebar

**Screenshots**
Sent privately using Twake

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 79

**Comment by RomaricMourgues** [comment]
For the QA:
- Send a message with code in it (using ''' [linebreack] some code [linebreack] ''' (and ` instead of ') ),
- Put a very long line in the code block (longer than the page width,
- Check the message block is not too large, for instance the edit/pin/react should be visible on the right while overing the message.
- If you open the side view (send message, add response, over message and click on the bottom right button "Show on the right") the content should not overlap.
