### ISSUE TITLE
Status does not update in all messages

### ISSUE THREAD

**Issue by chamerling** [TwakeApp/Twake#281]
**Describe the bug**

When use updates his status, it is not update everywhere directly but it seems that it is updated everywhere after sending a new message.

**To Reproduce**

1. Update the user status

**Expected behavior**

Status must be updated everywhere

**Screenshots**

I updated to 💊 🐙

![Capture d’écran 2020-09-23 à 08 37 38](https://user-images.githubusercontent.com/264403/93976046-a8e98300-fd78-11ea-8f8c-71b07c7c7e73.png)

Then after sending a new message, it is updated everywhere

![Capture d’écran 2020-09-23 à 08 42 17](https://user-images.githubusercontent.com/264403/93976178-dcc4a880-fd78-11ea-9b8c-0e14187a4ddd.png)

**Desktop (please complete the following information):**

OS X Chrome 85

**Comment by hantt12** [comment]
Hi @RomaricMourgues this is my observation:

User demo1 changes his status
Then user demo1 see his new status right after the changes it

However, user demo12, who has conversation with user demo1 (on different channel and direct message), does NOT see demo1's new status until demo12 refreshes the browser. 

I think we should enhance this too. Because after all, user updates status for others to see, not for himself

**Comment by RomaricMourgues** [comment]
Yes it doesn't work anymore, it seems to be a regression, thanks!
I create a "QA failed" column in ZenHub, do you want me to move it or will you do it ?

**Comment by hantt12** [comment]
I moved it. That's a good idea to create that column. Thanks
